name: Build LaTeX document

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: pdflatex main
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape

    - name: upload pdf as artifact
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ${{github.workspace}}/main.pdf
        retention-days: 14
