# This is the LaTeX workflow

name: Build LaTeX document

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2      
    - name: pdflatex main
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex
        compiler: pdflatex
        args: -interaction=nonstopmode -shell-escape
